### ISSUE TITLE
Dúvidas 2018

### ISSUE THREAD

**Issue by PauloBoaventura** [feliperoberto/correios-cep#2]
Este código esta funcionando em PHP 5, 5.6, 7.0, 7.1 ou até mesmo em 7.2 ?
São muitas dúvidas e nada pessoal... (Já deixo claro)
Este código esta nas normativas novas dos correios (2017) e que pelo visto já existe novas normativas em (2018)...
Bom, este não é o único que visualizamos que aparentemente esta tudo correto.
Mas, tenho que ser este USUÁRIO questionador, já que estamos enfrentando tantos problemas seja eles em PHP, AJAX ou qualquer impulso anterior á 2017.
E assim vem as dúvidas...

Gostaria de saber se podemos implementar este código em outras ferramentas e até mesmo em outas plataformas... 

Espero que tenhamos uma resposta satisfatória e um UPGRADE.

**Comment by feliperoberto** [comment]
Boa tarde Paulo, primeiramente desculpe-me pelo abandono do projeto, pois por algum motivo não vi ou recebi a notificação da abertura desta issue e apenas quase 1 ano depois apareci para discutirmos sobre.
Sinceramente não faço ideia se o código ainda funciona (na epoca foi escrito para rodar com o 5.2/3).
Sua principal dependência é o PHPQuery responsável por fazer o trabalho de mineirar os dados dentro do html. O problema dele era mantido pelo proprietário lá no Google Code, e até a época do encerramento do serviço não havia sido portado aqui para o GitHub (pelo que pesquisei há diversas forks e alternativas dele hoje). 
Quanto a um upgrade, podemos discutir sobre. Podemos fazer uma api mais concisa, seguindo psr e poder inclusive ser instalado via composer.
Fique a vontade para outras sugestões e até mesmo um PR.
Quanto a portar para outras plataformas, não há problema também. Até porque é uma aplicação de conceito simples (web scrapper), mas apenas verifique se já não há uma pronta em outra linguagem (afinal, quem sabe um PR não seja mais prático e interessante para sí e o outro projeto também).

**Comment by feliperoberto** [comment]
Boa noite @PauloBoaventura o código foi refatorado e já esta disponível em d66c8d2d584b95b25c898d577ebfe574a0d7e648
Embora testado apenas no 7.2, não deverá encontrar dificuldades ao rodar em versões anteriores do php. As classes estão mais autoexplicativas, e os respectivos exemplos mais claros. É possível inclusive instalar via composer e fazer deploy no Heroku.
